### ISSUE TITLE
achievements/check help

### ISSUE THREAD

**Issue by adl212** [ifvictr/nitrotype.js#7]
Hi, I'm not really sure what the ids part of this part would be used. Could you possibly help me on using this?

**Comment by ghost** [comment]
@adl212 Achievement IDs are listed in the [bootstrap](https://www.nitrotype.com/index/1/bootstrap.js).

**Comment by adl212** [comment]
@Ray-Adams I'm just unsure how to pass it as an argument. As you know, I'm more of a python guy.

**Comment by adl212** [comment]
@Ray-Adams How would I use the api with the get function?

**Comment by adl212** [comment]
And any idea what this means?
`{"success":false,"data":{"message":"Invalid Request.  Try refreshing the page.","uhuid":null,"suid":10092808,"sip":null,"rip":""}}`
I couldn't show the "rip" because that's my ip address.
